New workflows for OIDC publishing

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -4,6 +4,10 @@ on:
   push:
     branches: [main]
 
+permissions:
+  id-token: write
+  contents: write
+
 jobs:
   build:
     strategy:
@@ -16,6 +20,8 @@ jobs:
     steps:
       - name: Checkout Repository
         uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
 
       - name: Setup NodeJS
         uses: actions/setup-node@v4
@@ -25,7 +31,7 @@ jobs:
 
       - name: Build Package
         run: |
-          npm clean-install --ingnore-scripts
+          npm clean-install --ignore-scripts
           npm run build
 
   publish:
@@ -37,17 +43,18 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v4
         with:
-          token: ${{ secrets.repo_token }}
+          fetch-depth: 0
 
       - name: Setup NodeJS
         uses: actions/setup-node@v4
         with:
           registry-url: https://registry.npmjs.org
-          node-version: 20
+          node-version: 24
+
 
       - name: Build Package
         run: |
-          npm clean-install
+          npm clean-install --ignore-scripts
           npm run build
 
       - name: Publish Package
@@ -56,9 +63,11 @@ jobs:
 
           test -z "$(git ls-remote --tags origin "v${VERSION}")" || {
             echo "Release ${VERSION} already tagged, exiting..."
-            echo "::notice::Release ${VERSION} already tagged"
-            exit 0
+            echo "::error::Release ${VERSION} already tagged"
+            exit 1
           }
+
+          npm publish
 
           git config user.email 'developers@juit.com'
           git config user.name 'Github Workflows'
@@ -69,8 +78,26 @@ jobs:
             --title "Release ${VERSION}" \
             --target "${{ github.sha }}" \
             --verify-tag
-
-          npm publish
         env:
-          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
-          GH_TOKEN: ${{ secrets.repo_token }}
+          GH_TOKEN: ${{ github.token }}
+
+      - name: Send Email Notification
+        if: ${{ !success() }}
+        uses: dawidd6/action-send-mail@v6
+        with:
+          server_address: ${{ secrets.EMAIL_SERVER }}
+          username: ${{ secrets.EMAIL_USERNAME }}
+          password: ${{ secrets.EMAIL_PASSWORD }}
+          secure: true
+          convert_markdown: true
+          from: GitHub Actions <developers+github@juit.com>
+          to: Juit Developers <developers+github@juit.com>
+          subject: "[${{ job.status }}] ${{ github.workflow }} in ${{ github.repository }}"
+          body: |
+            The GitHub Action "${{ github.workflow }}" in repository "${{ github.repository }}" ${{ job.status == 'cancelled' && 'was canceled' || 'has failed' }}.
+
+            Build logs are available at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
+          html_body: |
+            The GitHub Action **`${{ github.workflow }}`** in repository **`${{ github.repository }}`** ${{ job.status == 'cancelled' && 'was **canceled**' || 'has **failed**' }}.
+
+            Build logs are available _[here](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})_.
